### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
added LICENSE in Readme

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@m09  please review

**Comment by vyaspranjal33** [comment]
@vmarkovtsev  please review

**Comment by m09** [comment]
DCO is not included. As mentioned in your numerous previous PRs this is required for us to merge.

**Comment by vyaspranjal33** [comment]
@m09  DCO included

**Comment by m09** [comment]
Ty :)

**Pull request merged**
